####################
#    Version 1.0   #
#     By: T0X1C    #
####################

#You can use the id or the name like this: 278 or diamond_pickaxe
Material: diamond_pickaxe

#This is the cooldown!!
CooldownTime: 4

#All the messages is stored here
Messages:
  #When the console tries to execute any commands
  OnlyPlayers: "&2PickaxeSell&a+ &8> &4Error: Only players can execute these commands!"
  #This message will show when a player activates.
  Enabled: "&2PickaxeSell&a+ &8> &aSucces: Enabled PickaxeSell!"
  #This message will show when a player deactivates.
  Disabled: "&2PickaxeSell&a+ &8> &eWarning: Disabled PickaxeSell!"
  #This message will show when a player reloads config.yml.
  Reload: "&2PickaxeSell&a+ &8> &aSuccess: Reloaded config.yml!"
  #This message will show when a player doesn't have permissions
  No-Permissions: "&2PickaxeSell&a+ &8> &4Error: You dont have permissions!"
  #This message will show when a player have disabled PickaxeSell.
  You-Have-Disabled: "&2PickaxeSell&a+ &8> &4Error: You have disabled PickaxeSell!"
  #This message will show when a player needs to wait.
  Time-Left: "&2PickaxeSell&a+ &8> &4Error: You must wait &6%time &7second(s)"
  #This message will show when a player types in /pick cooldown.
  Wrong-Cooldown-Command: "&2PickaxeSell&a+ &8> &4Error: /pick cooldown check!"
  #This message will show when a player checks if cooldown if while cooldown is off.
  Cooldown-False: "&2PickaxeSell&a+ &8> &6Status: Cooldown is &4&lOFF"
  #This message will show when a player checks if cooldown if while cooldown is on.
  Cooldown-True: "&2PickaxeSell&a+ &8> &6Status: Cooldown is &a&lON"
  
  #AutoSell messages
  #When you try to sell 0 blocks
  NoBlocks: "&2PickaxeSell&a+ &8> &4Error: You dont have any blocks that could be sold!"
  #When you don't have a shop to sell to
  NoShop: "&2PickaxeSell&a+ &8> &4Error: You dont have any shops to sell to!"
  #When you successfully sold items
  Success: "&2PickaxeSell&a+ &8> &aSuccess: You sold %items% items and earned &a$&7%amount%"

Settings:
  #If this is not enabled the plugin will automatically use QuickSell
  AutoSellHook: true
  #If there should be a cooldown or not
  Cooldown: true