####################
#    Version 1.1   #
#     By: T0X1C    #
####################

messages:
  #Only players can use these commands :D
  only-players: "&2PickaxeSell&a+ &8> &4Error: &7Only players can execute these commands!"
  #When the person doesn't have the permission to do something
  no-permissions: "&2PickaxeSell&a+ &8> &4Error: &7You dont have permissions!"
  #When someone successfully enabled PickaxeSell+
  enabled: "&2PickaxeSell&a+ &8> &aSucces: &7Enabled!"
  #When someone successfully disabled PickaxeSell+
  disabled: "&2PickaxeSell&a+ &8> &eWarning: &7Disabled!"
  #When you or a person reloads the config
  reload: "&2PickaxeSell&a+ &8> &aSuccess: &7Reloaded config.yml!"
  #When you or a person tries to use PickaxeSell+.. but you or the person disabled it
  you-have-disabled: "&2PickaxeSell&a+ &8> &4Error: &7You have disabled PickaxeSell!"
  #How much time there's left before you or person can use it again
  time-left: "&2PickaxeSell&a+ &8> &4Error: &7You must wait &e%time &7second(s)"
  #When someone only types /pick cooldown
  wrong-cooldown-command: "&2PickaxeSell&a+ &8> &4Error: &7/pick cooldown check!"
  #When the cooldown is not on
  cooldown-false: "&2PickaxeSell&a+ &8> &6Status: &7Cooldown is &4&lOFF"
  #When the cooldown is on
  cooldown-true: "&2PickaxeSell&a+ &8> &6Status: &7Cooldown is &a&lON"
  
  #AutoSell messages
  #When you try to sell 0 blocks
  no-blocks: "&2PickaxeSell&a+ &8> &4Error: &7You dont have any blocks that could be sold!"
  #When you don't have a shop to sell to
  no-shop: "&2PickaxeSell&a+ &8> &4Error: &7You dont have any shops to sell to!"
  #When you successfully sold your items
  success: "&2PickaxeSell&a+ &8> &aSuccess: &7You sold %items% items and earned &a$&7%amount%"
  
  #When AutoSell is not installed and autosell-hook is enabled
  no-autosell: "&2PickaxeSell&a+ &8> &4Error: &7Sorry but you forgot to install AutoSell!"
  #When QuickSell is not installed and autosell-hook is disabled
  no-quicksell: "&2PickaxeSell&a+ &8> &4Error: &7Sorry but you forgot to install QuickSell!"

settings:
  #If this is not enabled the plugin will automatically use QuickSell
  autosell-hook: true
  #If there should be a cooldown or not
  cooldown: true
  #This is the cooldown!!
  #Note: this is kinda gonna be 
  cooldown-time: 5
  #You can use the id or the name like this: 278 or diamond_pickaxe
  material: diamond_pickaxe